name: input_to_the_workflow

on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Preson_to_greet'
                default: 'world'
                required: true

jobs:
    greet:

        runs-on: ubuntu-latest

        steps:
            - name: send_greet
              run: echo "hello, ${{ github.event.inputs.name }}"